name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to personal repository
        run: |
          git remote add mirror https://x-access-token:${{ secrets.DEVS_PAT }}@github.com/devrecsoc/devs-results.git
          git push mirror --force main