name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repository
        env:
          SOURCE_REPO: ${{ github.repository }}
          TARGET_REPO: devrecsoc/devs-results
          SOURCE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_TOKEN: ${{ secrets.DEVS_PAT }}
        run: |
          set -euo pipefail

          echo "git version: $(git --version)"

          git clone --bare https://x-access-token:${SOURCE_TOKEN}@github.com/${SOURCE_REPO}.git repo.git
          cd repo.git

          git remote add target https://x-access-token:${TARGET_TOKEN}@github.com/${TARGET_REPO}.git

          # Push branches
          git push --prune target 'refs/heads/*:refs/heads/*'

          # Push tags
          git push target --tags
