name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check secret
        run: |
          if [ -z "${{ secrets.DEVS_PAT }}" ]; then
            echo "DEVS_PAT is EMPTY"
            exit 1
          else
            echo "DEVS_PAT exists"
          fi

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push mirror
        run: |
          git remote add mirror https://x-access-token:${{ secrets.DEVS_PAT }}@github.com/devrecsoc/devs-results.git
          git push --verbose mirror main --force
